# Generated by Django 4.0 on 2022-01-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='No Bio', max_length=64),
        ),
    ]
