# Generated by Django 4.0 on 2022-01-23 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_user_bio_user_followers_user_followings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followers',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='followings',
            new_name='following',
        ),
    ]
