# Generated by Django 4.0 on 2022-01-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_user_bio_user_follower_user_following_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
