# Generated by Django 4.0 on 2022-01-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_user_followers_alter_follow_from_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='network_follow_unique_relationships',
        ),
    ]
