# Generated by Django 4.0 on 2022-01-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_remove_follow_network_follow_unique_relationships'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='network_follow_unique_relationships'),
        ),
    ]
