# Generated by Django 4.0 on 2022-01-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_remove_user_follower_remove_user_following_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='following',
            new_name='followings',
        ),
    ]
