# Generated by Django 4.0 on 2022-01-27 15:21

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0026_userfollowing_network_userfollowing_unique_relationships'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userfollowing',
            constraint=models.CheckConstraint(check=models.Q(('from_user', django.db.models.expressions.F('to_user')), _negated=True), name='network_userfollowing_prevent_self_follow'),
        ),
    ]
