# Generated by Django 4.0 on 2022-01-27 15:26

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0027_userfollowing_network_userfollowing_prevent_self_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userfollowing',
            name='network_userfollowing_unique_relationships',
        ),
        migrations.RemoveConstraint(
            model_name='userfollowing',
            name='network_userfollowing_prevent_self_follow',
        ),
        migrations.AddConstraint(
            model_name='userfollowing',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_relationships'),
        ),
        migrations.AddConstraint(
            model_name='userfollowing',
            constraint=models.CheckConstraint(check=models.Q(('from_user', django.db.models.expressions.F('to_user')), _negated=True), name='prevent_self_follow'),
        ),
    ]
