# Generated by Django 4.0 on 2022-01-28 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0029_user_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follower',
            new_name='followers',
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='network.user'),
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='network.user'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
